// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_-PF1coI4rg1MOu0CumTO0CdSPeS-po',
    appId: '1:334903686980:web:c4a2e7c38ab81357240911',
    messagingSenderId: '334903686980',
    projectId: 'talentpitchmock',
    authDomain: 'talentpitchmock.firebaseapp.com',
    storageBucket: 'talentpitchmock.appspot.com',
    measurementId: 'G-Q5FVESL5C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8fepeE2FF0fbYxkiCPjI0STFYhHnYFpw',
    appId: '1:334903686980:android:c6812a6146892586240911',
    messagingSenderId: '334903686980',
    projectId: 'talentpitchmock',
    storageBucket: 'talentpitchmock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIJKK77hRNIWZEAHPD-MQSbeOYSsZmN7c',
    appId: '1:334903686980:ios:5b904d91e63738d8240911',
    messagingSenderId: '334903686980',
    projectId: 'talentpitchmock',
    storageBucket: 'talentpitchmock.appspot.com',
    iosBundleId: 'com.example.talentSeek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIJKK77hRNIWZEAHPD-MQSbeOYSsZmN7c',
    appId: '1:334903686980:ios:5b904d91e63738d8240911',
    messagingSenderId: '334903686980',
    projectId: 'talentpitchmock',
    storageBucket: 'talentpitchmock.appspot.com',
    iosBundleId: 'com.example.talentSeek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp_-PF1coI4rg1MOu0CumTO0CdSPeS-po',
    appId: '1:334903686980:web:764d19526bf11433240911',
    messagingSenderId: '334903686980',
    projectId: 'talentpitchmock',
    authDomain: 'talentpitchmock.firebaseapp.com',
    storageBucket: 'talentpitchmock.appspot.com',
    measurementId: 'G-YBQN9F4KQ5',
  );
}
